import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import StoreProvider from "@/lib/redux/StoreProvider";
import AuthProvider from "@/components/auth/AuthProvider";
import { Geist } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

const geist = Geist({ subsets: ["latin"], variable: "--font-geist", display: "swap" });

export const metadata: Metadata = {
  title: "Mono repo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(geist.className, "h-full", "antialiased")}>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <AuthProvider>
          <Toaster position="top-center" toastOptions={{ unstyled: true }} />
          <StoreProvider>{children}</StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
